project:
  type: website
  preview: 
    port: 3000
    browser: false
  

execute:
  freeze: auto

website:
  title: "Vela Ligera"
  page-navigation: true      
  navbar:
    right:
      - href: pages/partes.qmd
      - href: pages/vientos.qmd
      - href: pages/categorias.qmd
      - text: Laser
        menu:       
        - href: pages/laser.qmd
          text: Categoría Laser
        - href: www.gooogle.com
          text: Vídeo Laser
  sidebar: 
    alignment: left
  search: 
    type: textbox
  page-footer:
    left: Educación Física
    center: Javier Ribal del Río 1º Bachillerato A Nº 23
    right: Curso 2022-23
    background: info
  
    
  

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    toc-title: Índice
    number-sections: true
    code-overflow: wrap
    highlight-style: arrow