project:
  type: website
  preview: 
    port: 3000
    browser: false
  

execute:
  freeze: auto

website:
  title: "Trabajo-EF-Vela"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true



